export const SHOP_INFOR_REQUEST = "SHOP_INFOR_REQUEST";
export const SHOP_INFOR_SUCCESS = "SHOP_INFOR_SUCCESS";
export const SHOP_INFOR_FAIL = "SHOP_INFOR_FAIL";

export const UPDATE_INFOR_REQUEST = "UPDATE_INFOR_REQUEST";
export const UPDATE_INFOR_SUCCESS = "UPDATE_INFOR_SUCCESS";
export const UPDATE_INFOR_FAIL = "UPDATE_INFOR_FAIL";
