export const CHECK_OTP_REQUEST = "CHECK_OTP_REQUEST";
export const CHECK_OTP_SUCCESS = "CHECK_OTP_SUCCESS";
export const CHECK_OTP_FAIL = "CHECK_OTP_FAIL";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";
export const USER_SIGNOUT = "USER_SIGNOUT";

export const USER_SIGNINGG_REQUEST = "USER_SIGNINGG_REQUEST";
export const USER_SIGNINGG_SUCCESS = "USER_SIGNINGG_SUCCESS";
export const USER_SIGNINGG_FAIL = "USER_SIGNINGG_FAIL";

export const USER_SIGNINFB_REQUEST = "USER_SIGNINFB_REQUEST";
export const USER_SIGNINFB_SUCCESS = "USER_SIGNINFB_SUCCESS";
export const USER_SIGNINFB_FAIL = "USER_SIGNINFB_FAIL";

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET';


export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';